# Generated by Django 6.0 on 2025-12-12 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('engagements', models.IntegerField(default=0)),
                ('conversions', models.IntegerField(default=0)),
                ('spend', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='campaigns.campaign')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('campaign', 'date')},
            },
        ),
    ]
